CREATE TABLE FOOD_CATEGORY (
    ID number(2,0) CONSTRAINT pk_food_category_id primary key,
    CATEGORY varchar2(20) CONSTRAINT nn_food_category_category not NULL

);

ALTER TABLE FOOD_CATEGORY MODIFY (CATEGORY varchar2(50));

INSERT INTO FOOD_CATEGORY (ID, CATEGORY) VALUES (1, '축산/계란');
INSERT INTO FOOD_CATEGORY (ID, CATEGORY) VALUES (2, '수산물');
INSERT INTO FOOD_CATEGORY (ID, CATEGORY) VALUES (3, '소스/장');
INSERT INTO FOOD_CATEGORY (ID, CATEGORY) VALUES (4, '유제품/아이스크림');
INSERT INTO FOOD_CATEGORY (ID, CATEGORY) VALUES (5, '음료/생수');
INSERT INTO FOOD_CATEGORY (ID, CATEGORY) VALUES (6, '과일/채소');
INSERT INTO FOOD_CATEGORY (ID, CATEGORY) VALUES (7, '밀키트/간편요리');